name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - 'feature/**/**'

jobs:
  eslint:
    timeout-minutes: 2
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run ESLint
        run: eslint . --ext .js
