name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - 'feature/**/**'

jobs:
  eslint:
    timeout-minutes: 2
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3

      - name: Fetching actions repo
        uses: actions/checkout@v3
        with:
          repository: wtc-cdm/wtc-github-actions
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: ./.github/actions

      - name: npm ci
        continue-on-error: true
        run: npm ci

      - name: Run ESLint
        uses: ./.github/actions/action-eslint-master
        with:
          reporter: github-check
